kubeconfig: '/var/run/kubernetes/admin.kubeconfig'
resync_interval: 30m
prometheus_enabled: true
sink: glog

kafka:
  brokers:
    - localhost:9092
  topic: eventrouter
  async: true
  retryMax: 5
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-256
    user: test
    password: testpw
  tls:
    rootCAFiles:
      - rootCA.pem
    certFile: ''
    keyFile: ''
    insecureSkipVerify: true

httpSinkUrl: 'http://localhost:8080'
httpSinkBufferSize: 1500
httpSinkDiscardMessages: true
rocksetAPIKey: ''
rocksetCollectionName: ''
rocksetWorkspaceName: ''
s3SinkAccessKeyID: ''
s3SinkSecretAccessKey: ''
s3SinkRegion: ap-south-1
s3SinkBucket: ''
s3SinkBucketDir: ''
s3SinkBufferSize: 1500
s3SinkDiscardMessages: true
s3SinkOutputFormat: flatjson
s3SinkUploadInterval: 120
